name: otis
description: A mobile UI for OTIS

version: 1.0.14+10

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: 0.13.3
  image_picker: 0.8.0+3
  video_player: 2.1.6
  chewie: 1.2.2
  flutter_secure_storage: 4.2.0
  flutter_bloc: 7.0.1
  meta: 1.3.0
  equatable: 2.0.3
  validators: 3.0.0
  material_design_icons_flutter: 4.0.5955
  flutter_full_pdf_viewer: 1.0.6
  datetime_picker_formfield: 2.0.0
  flutter_cache_manager: 3.1.2
  video_compress: 3.0.0
  file_picker: 3.0.2+2
  path_provider: 2.0.2
  page_transition: 2.0.2
  azlistview: 1.1.1
  progress_dialog: 1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
